branch: main
compact: true
download-external-modules: true 
evaluate-variables: true 
external-modules-download-path:
framework: all 
output: cli 
quiet: true 
skip-check: 
  - CKV2_AWS_6
  - CKV_AWS_144
skip-fixes: false 
skip-suppressions: true 
soft-fail: true