download-external-modules: true
evaluate-variables: true
external-modules-download-path:
framework: all
output: cli
skip-fixes: true
soft-fail: true
compact: true
skip-check: 
  - CKV2_AWS_6
  - CKV_AWS_144