name: 'CI'
on:
  # pull_request:
  #   paths-ignore: [ '**.md' ]
  # push:
  #   paths-ignore: [ '**.md' ]
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      directory:
        description: "directory"
        required: true
        default: "introduction"

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Scan with Checkov
        run: |
          checkov -d ${{ github.event.inputs.directory }} -o junitxml > ${{ github.event.inputs.directory }}/checkov-report.xml

      - name: Upload results
        uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: ${{ github.event.inputs.directory }}/checkov-report.xml