name: 'CI'
on:
  # pull_request:
  #   paths-ignore: [ '**.md' ]
  # push:
  #   paths-ignore: [ '**.md' ]
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      directory:
        description: "directory"
        required: true
        default: "introduction"

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.7]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Scan with Checkov
        run: |
          docker run --volume `pwd`/${{ github.event.inputs.directory }}:/${{ github.event.inputs.directory }} bridgecrew/checkov \
            --directory /${{ github.event.inputs.directory }} --output junitxml > `pwd`/${{ github.event.inputs.directory }}/ci-report.xml

      - name: Delete docker process
        run: |
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)

      - name: Publish Checkov scan result
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ${{ github.event.inputs.directory }}/ci-report.xml

      - name: Upload results
        uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: ci-results
          path: ${{ github.event.inputs.directory }}/ci-report.xml