name: 'PLAN'
on:
  workflow_dispatch:
    inputs:
      directory:
        description: "directory"
        required: true
        default: "introduction"

jobs:
  plan-scan:
    name: Plan scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.event.inputs.directory }}
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Checkov
        run: pip install checkov

      - name: Checkov version
        run: checkov -v

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.5

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan --out tfplan.binary

      - name: Terraform Show
        id: show
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Scan with Checkov
        run: |
          cat tfplan.json
          checkov -f tfplan.json -o junitxml > checkov-report.xml
          
      - name: Upload results
        uses: actions/upload-artifact@v2  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: ${{ github.event.inputs.directory }}/checkov-report.xml