name: CI Scanner
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      directory:
        description: "directory name"
        required: true
        default: "introduction"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run test script that scans Kubernetes config
        run: ./test.sh
      
      - name: Run box version
        uses: docker://bridgecrew/checkov:latest
        with:
          entrypoint: /opt/box/box
          args: version